name: CI
on: [push, pull_request]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    name: Cleanup previous runs
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run linter
        run: make lint
        
  test:
    runs-on: ubuntu-latest
    name: Test on Python {{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: pip install tox
      - name: Run tests
        run: tox -e py
    
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build
        run: make build
        
  docker:
    name: Build Docker images 
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract Docker metadata
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: hoffmannlaroche/gcasc
        tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}.{{minor}}.{{patch}}
    - name: Build Docker image and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          latest
        labels: ${{ steps.docker_meta.outputs.labels }}
