name: Contributors
on:
  push:
    branches:
      - master

jobs:
  contributors:
    name: Add Conributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'docs(readme): update contributors'
          committer_username: 'Contribution Bot'
          image_size: 80
          columns_per_row: 7